spring:
  -application.name: Project
  -datasource:
    -url: jdbc:postgresql://localhost:5432/postgres
    -username: postgres
    -password: root
    -driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

vk:
  -api:
    -version: 5.131
    # Может потребоваться обновление токена! С помощью токена возможно управлять аккаунтом. Срок жизни = 1 час
    # Получить: https://vkhost.github.io/
    -access-token: token

default:
  profile:
    picture:
      url: https://cdn.pixabay.com/photo/2023/10/03/10/49/anonymous-8291223_1280.png